name: conan-package

on:
  push:
    paths:
      - 'plugins/**'
      - 'cura/**'
      - 'resources/bundled_packages/**'
      - 'resources/i18n/**'
      - 'resources/qml/**'
      - 'resources/setting_visibility/**'
      - 'resources/shaders/**'
      - 'resources/texts/**'
      - 'resources/themes/**'
      - 'resources/public_key.pem'
      - 'resources/README_resources.txt'
      - 'icons/**'
      - 'tests/**'
      - 'packaging/**'
      - '.github/workflows/conan-package.yml'
      - '.github/workflows/notify.yml'
      - '.github/workflows/requirements-runner.txt'
      - 'requirements*.txt'
      - 'conanfile.py'
      - 'conandata.yml'
      - '*.jinja'
    branches:
      - 'main'
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'

jobs:
  conan-package:
    uses: yeelam-gordon/cura-workflows/.github/workflows/conan-package.yml@09b078f7642941d15b39a0a8f3a31db2dac65976
    with:
      cura_workflows_ref: 09b078f7642941d15b39a0a8f3a31db2dac65976
      allow_non_default_branch_package_create: true
      platform_linux: false
      platform_windows: false
      platform_mac: false
      platform_windows_arm64: true
      platform_wasm: false
    secrets: inherit
