name: conan-package

on:
  push:
    paths:
      - 'plugins/**'
      - 'cura/**'
      - 'resources/bundled_packages/**'
      - 'resources/i18n/**'
      - 'resources/qml/**'
      - 'resources/setting_visibility/**'
      - 'resources/shaders/**'
      - 'resources/texts/**'
      - 'resources/themes/**'
      - 'resources/public_key.pem'
      - 'resources/README_resources.txt'
      - 'icons/**'
      - 'tests/**'
      - 'packaging/**'
      - '.github/workflows/conan-package.yml'
      - '.github/workflows/notify.yml'
      - '.github/workflows/requirements-runner.txt'
      - 'requirements*.txt'
      - 'conanfile.py'
      - 'conandata.yml'
      - '*.jinja'
    branches:
      - 'main'
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'

jobs:
  conan-package:
    uses: yeelam-gordon/cura-workflows/.github/workflows/conan-package.yml@9c2757ee4777fe2efc3579c0423948e751e3a842
    with:
      cura_workflows_ref: 9c2757ee4777fe2efc3579c0423948e751e3a842
      allow_non_default_branch_package_create: true
      validation_skip_recipe_upload: true
      validation_mpdecimal_recipe_ref: 95f795b645dfb6d3dbaf4bc60ad82f18e867b175
      validation_conan_config_ref: 0e52074c82aefdf6d4aca8e0288824db173a0550
      validation_conan_cache_key: cura-arm64-deps-v1-b9f8f72d-e54e2a0-95f795b6-0e52074c
      validation_uranium_ref: ff02e1f59e67042a2a5d5cada665ed75dcbe55bd
      validation_iocpsupport_ref: ada4db6f928f2a4f9540fe527c32044f6b018729
      platform_linux: false
      platform_windows: false
      platform_mac: false
      platform_windows_arm64: true
      platform_wasm: false
    secrets: inherit
