name: Windows ARM Installer
run-name: ${{ inputs.cura_conan_version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      cura_conan_version:
        description: 'Cura Conan Version'
        default: ''
        type: string
      package_overrides:
        description: 'List of specific packages to be used (space-separated)'
        default: ''
        type: string
      conan_args:
        description: 'Conan args'
        default: ''
        required: false
        type: string
      enterprise:
        description: 'Build Cura as an Enterprise edition'
        default: false
        required: true
        type: boolean
      staging:
        description: 'Use staging API'
        default: false
        required: true
        type: boolean
      operating_system:
        description: 'OS'
        required: true
        default: 'self-hosted-Windows-ARM64'
        type: choice
        options:
          - self-hosted-Windows-ARM64
      package_workflow_run_id:
        description: 'Validated package workflow run ID'
        required: true
        type: string
      package_workflow_run_attempt:
        description: 'Validated package workflow run attempt'
        required: true
        type: string

jobs:
  windows-installer:
    uses: yeelam-gordon/cura-workflows/.github/workflows/cura-installer-windows-arm.yml@d291a51904c6f7cb3dc1300ac31b67ba634a4427
    with:
      cura_conan_version: ${{ inputs.cura_conan_version }}
      package_overrides: ${{ inputs.package_overrides }}
      conan_args: ${{ inputs.conan_args }}
      enterprise: ${{ inputs.enterprise }}
      staging: ${{ inputs.staging }}
      operating_system: ${{ inputs.operating_system }}
      signing_operating_system: self-hosted-Windows-X64
      cura_workflows_ref: d291a51904c6f7cb3dc1300ac31b67ba634a4427
      package_workflow_run_id: ${{ inputs.package_workflow_run_id }}
      package_workflow_run_attempt: ${{ inputs.package_workflow_run_attempt }}
    secrets: inherit
